Always build and use own rebar
This solves issues with incompatible with systems that provides
old rebar versions.

Package maintainers still can override our rebar with system one
with --rebar command line option. By doing this, they obligates to
provide rebar of valid version.

Current version is pinned to 2.6.0 which is the minimal of
supported.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -66,6 +66,7 @@ Options:
   --disable-fauxton           do not build Fauxton
   --disable-docs              do not build any documentation or manpages
   --skip-deps                 do not update erlang dependencies
+  --rebar=PATH                use rebar by specified path (version >=2.6.0 && <3.0 required)
 
 
   Installation directories:
@@ -126,6 +127,22 @@ parse_opts() {
                 SKIP_DEPS=1
                 shift
                 continue
+                ;;
+
+            --rebar)
+                if [ -x "$2" ]; then
+                    version=`$2 --version 2> /dev/null | grep -o "2\.[6-9]\.[0-9]"`
+                    if [ $? -ne 0 ]; then
+                        printf 'Rebar >=2.6.0 and <3.0.0 required' >&2
+                        exit 1
+                    fi
+                    eval REBAR=$2
+                    shift 2
+                    continue
+                else
+                    printf 'ERROR: "--rebar" requires valid path to executable.\n' >&2
+                    exit 1
+                fi
                 ;;
 
             --user|-u)
@@ -632,8 +649,24 @@ cat > $rootdir/config.erl << EOF
 EOF
 
 
+function install_local_rebar(){
+  if [ ! -x "${rootdir}/bin/rebar" ]; then
+      git clone --depth 1 --branch 2.6.0 https://git-wip-us.apache.org/repos/asf/couchdb-rebar.git ${rootdir}/src/rebar
+      make -C ${rootdir}/src/rebar
+      mv ${rootdir}/src/rebar/rebar ${rootdir}/bin/rebar
+      make -C ${rootdir}/src/rebar clean
+  fi
+}
+
+
+if [ -z "${REBAR}" ]; then
+    install_local_rebar
+    REBAR=${rootdir}/bin/rebar
+fi
+
+
 # only update dependencies, when we are not in a release tarball
 if [ -d .git  -a $SKIP_DEPS -ne 1 ]; then
   echo "==> updating dependencies"
-  rebar get-deps update-deps
+  ${REBAR} get-deps update-deps
 fi
